# Generated by Django 3.2.9 on 2022-02-09 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductCode', models.CharField(max_length=64)),
                ('ProductName', models.CharField(max_length=255)),
                ('SellingPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('InvoiceNumber', models.CharField(max_length=64)),
                ('InvoiceDate', models.DateField()),
                ('CustomerName', models.CharField(max_length=255)),
                ('TotalAmount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceDetails',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('LineNumber', models.IntegerField()),
                ('Productname', models.CharField(max_length=255)),
                ('Quantity', models.IntegerField()),
                ('UnitPrice', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('SalesInvoiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salesinvoice')),
            ],
        ),
    ]
